const ExcelJS = require("exceljs");

class ExcelService {

    static async generateEmergencyReport(reports, statistics, res) {

        const workbook = new ExcelJS.Workbook();

        workbook.creator = "SafeConnect";
        workbook.created = new Date();

        const worksheet = workbook.addWorksheet("Emergency Reports");

        // ===========================
        // TITLE
        // ===========================

        worksheet.mergeCells("A1:F1");
        worksheet.getCell("A1").value = "SAFECONNECT";
        worksheet.getCell("A1").font = {
            bold: true,
            size: 20
        };
        worksheet.getCell("A1").alignment = {
            horizontal: "center"
        };

        worksheet.mergeCells("A2:F2");
        worksheet.getCell("A2").value =
            "Community Disaster and Emergency Response System";
        worksheet.getCell("A2").alignment = {
            horizontal: "center"
        };

        worksheet.mergeCells("A3:F3");
        worksheet.getCell("A3").value =
            "Emergency Incident Report";
        worksheet.getCell("A3").font = {
            bold: true,
            size: 14
        };
        worksheet.getCell("A3").alignment = {
            horizontal: "center"
        };

        worksheet.getCell("A5").value =
            `Generated: ${new Date().toLocaleString()}`;

        // ===========================
        // SUMMARY
        // ===========================

        worksheet.getCell("A7").value = "Summary";
        worksheet.getCell("A7").font = { bold: true };

        worksheet.getCell("A8").value = "Total Reports";
        worksheet.getCell("B8").value = statistics.totalReports;

        worksheet.getCell("A9").value = "Pending";
        worksheet.getCell("B9").value = statistics.pending;

        worksheet.getCell("A10").value = "Dispatched";
        worksheet.getCell("B10").value = statistics.dispatched;

        worksheet.getCell("A11").value = "In Progress";
        worksheet.getCell("B11").value = statistics.inProgress;

        worksheet.getCell("A12").value = "Resolved";
        worksheet.getCell("B12").value = statistics.resolved;

        worksheet.getCell("A13").value = "Cancelled";
        worksheet.getCell("B13").value = statistics.cancelled;

        // ===========================
        // TABLE
        // ===========================

        const headerRow = 15;

        worksheet.columns = [
            { header: "Reference", key: "reference", width: 22 },
            { header: "Emergency", key: "emergency", width: 20 },
            { header: "Reporter", key: "reporter", width: 28 },
            { header: "Location", key: "location", width: 30 },
            { header: "Status", key: "status", width: 18 },
            { header: "Date", key: "date", width: 20 }
        ];

        const headers = worksheet.getRow(headerRow);

        headers.values = [
            "Reference",
            "Emergency",
            "Reporter",
            "Location",
            "Status",
            "Date"
        ];

        headers.font = {
            bold: true
        };

        headers.eachCell((cell) => {
            cell.alignment = {
                horizontal: "center"
            };
            cell.border = {
                top: { style: "thin" },
                left: { style: "thin" },
                bottom: { style: "thin" },
                right: { style: "thin" }
            };
        });

        // ===========================
        // DATA
        // ===========================

        let currentRow = headerRow + 1;

        reports.forEach((report) => {

            worksheet.getCell(`A${currentRow}`).value =
                report.report_reference;

            worksheet.getCell(`B${currentRow}`).value =
                report.emergency_type;

            worksheet.getCell(`C${currentRow}`).value =
                report.reporter;

            worksheet.getCell(`D${currentRow}`).value =
                report.location;

            worksheet.getCell(`E${currentRow}`).value =
                report.status;

            worksheet.getCell(`F${currentRow}`).value =
                new Date(report.created_at).toLocaleDateString();

            for (let i = 1; i <= 6; i++) {

                worksheet.getRow(currentRow).getCell(i).border = {
                    top: { style: "thin" },
                    left: { style: "thin" },
                    bottom: { style: "thin" },
                    right: { style: "thin" }
                };

            }

            currentRow++;

        });

        // ===========================
        // FOOTER
        // ===========================

        currentRow += 2;

        worksheet.getCell(`A${currentRow}`).value =
            "Generated by SafeConnect";

        worksheet.getCell(`A${currentRow + 1}`).value =
            "This report was generated electronically.";

        // ===========================
        // DOWNLOAD
        // ===========================

        res.setHeader(
            "Content-Type",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        );

        res.setHeader(
            "Content-Disposition",
            `attachment; filename=Emergency_Report_${Date.now()}.xlsx`
        );

        await workbook.xlsx.write(res);

        res.end();

    }

}

module.exports = ExcelService;