const fs = require("fs");
const path = require("path");
const ExcelJS = require("exceljs");
const STYLE = require("../config/reportStyle");

// Generic, branded table-report Excel generator -- the Excel counterpart to
// pdfService.js. See that file's comment for the shared design: category
// specific field mapping stays in exportService.js.
class ExcelService {

    // options: same shape as PDFService.generateTableReport
    //   reportTitle, filenamePrefix, summary: [{label, value}],
    //   columns: [{label, width}], rows: [[...cells]]
    static async generateTableReport(options, res) {
        const {
            reportTitle,
            filenamePrefix,
            subtitle,
            summary = [],
            columns,
            rows
        } = options;

        const workbook = new ExcelJS.Workbook();
        workbook.creator = "SafeConnect";
        workbook.created = new Date();

        const sheetName = reportTitle.length > 31 ? reportTitle.slice(0, 31) : reportTitle;
        const worksheet = workbook.addWorksheet(sheetName || "Report");

        const lastColLetter = String.fromCharCode(65 + Math.max(columns.length - 1, 0));

        worksheet.mergeCells(`A1:${lastColLetter}1`);
        worksheet.getCell("A1").value = "SAFECONNECT";
        worksheet.getCell("A1").font = { bold: true, size: 20 };
        worksheet.getCell("A1").alignment = { horizontal: "center" };

        worksheet.mergeCells(`A2:${lastColLetter}2`);
        worksheet.getCell("A2").value = "Community Disaster and Emergency Response System";
        worksheet.getCell("A2").alignment = { horizontal: "center" };

        worksheet.mergeCells(`A3:${lastColLetter}3`);
        worksheet.getCell("A3").value = reportTitle;
        worksheet.getCell("A3").font = { bold: true, size: 14 };
        worksheet.getCell("A3").alignment = { horizontal: "center" };

        if (subtitle) {
            worksheet.mergeCells(`A4:${lastColLetter}4`);
            worksheet.getCell("A4").value = subtitle;
            worksheet.getCell("A4").alignment = { horizontal: "center" };
        }

        worksheet.getCell("A5").value = `Generated: ${new Date().toLocaleString("en-PH", { timeZone: "Asia/Manila" })}`;

        // Logos (config/reportStyle.js) in the top-left and top-right
        // corners, over the title rows. Missing files are simply skipped.
        [1, 2, 3].forEach((r) => { worksheet.getRow(r).height = 22; });
        const addLogo = (logo, col) => {
            if (!logo.file || !fs.existsSync(logo.file)) return;
            const extension = path.extname(logo.file).slice(1).toLowerCase().replace("jpg", "jpeg");
            const imageId = workbook.addImage({ filename: logo.file, extension });
            worksheet.addImage(imageId, { tl: { col, row: 0 }, ext: { width: 80, height: 80 } });
        };
        addLogo(STYLE.logos.left, 0.1);
        addLogo(STYLE.logos.right, Math.max(columns.length - 1, 0) + 0.3);

        let nextRow = 7;

        if (summary.length) {
            worksheet.getCell(`A${nextRow}`).value = "Summary";
            worksheet.getCell(`A${nextRow}`).font = { bold: true };
            nextRow++;

            summary.forEach(({ label, value }) => {
                worksheet.getCell(`A${nextRow}`).value = label;
                worksheet.getCell(`B${nextRow}`).value = value;
                nextRow++;
            });

            nextRow++;
        }

        const headerRow = nextRow;

        // Widths only: giving exceljs a `header` here writes the column labels
        // into row 1, over the SAFECONNECT title. The header row is written below.
        columns.forEach((col, i) => {
            worksheet.getColumn(i + 1).width = col.excelWidth || 22;
        });

        const headerRowRef = worksheet.getRow(headerRow);
        headerRowRef.values = columns.map((c) => c.label);
        headerRowRef.font = { bold: true };
        headerRowRef.eachCell((cell) => {
            cell.alignment = { horizontal: "center" };
            cell.border = {
                top: { style: "thin" }, left: { style: "thin" },
                bottom: { style: "thin" }, right: { style: "thin" }
            };
        });

        let currentRow = headerRow + 1;

        rows.forEach((row) => {
            row.forEach((cellValue, i) => {
                worksheet.getCell(currentRow, i + 1).value = cellValue ?? "";
            });

            for (let i = 1; i <= columns.length; i++) {
                worksheet.getRow(currentRow).getCell(i).border = {
                    top: { style: "thin" }, left: { style: "thin" },
                    bottom: { style: "thin" }, right: { style: "thin" }
                };
            }

            currentRow++;
        });

        currentRow += 2;
        worksheet.getCell(`A${currentRow}`).value = "Generated by SafeConnect";
        worksheet.getCell(`A${currentRow + 1}`).value = "This report was generated electronically.";

        // Build into memory first, same reasoning as pdfService.js: writing
        // straight to `res` can flush response headers before an error
        // later in the process has a chance to be caught cleanly.
        const buffer = await workbook.xlsx.writeBuffer();

        res.setHeader(
            "Content-Type",
            "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        );
        res.setHeader(
            "Content-Disposition",
            `attachment; filename=${filenamePrefix}_${Date.now()}.xlsx`
        );

        res.end(buffer);
    }
}

module.exports = ExcelService;