const PDFDocument = require("pdfkit");

class PDFService {
    static generateEmergencyReport(reports, stats, res) {
        const doc = new PDFDocument({
            size: "A4",
            margin: 50
        });

        // Response headers
        res.setHeader("Content-Type", "application/pdf");
        res.setHeader(
            "Content-Disposition",
            `attachment; filename=Emergency_Report_${Date.now()}.pdf`
        );

        doc.pipe(res);

// -------------------------
// HEADER
// -------------------------
        doc
            .fontSize(22)
            .font("Helvetica-Bold")
            .text("SAFECONNECT", {
                align: "center"
            });

        doc
            .fontSize(12)
            .font("Helvetica")
            .text("Community Disaster and Emergency Response System", {
                align: "center"
            });

        doc.text("Barangay Santa Fe, Dasmarinas, Cavite", {
            align: "center"
        });

        doc.moveDown();

        doc
            .moveTo(50, doc.y)
            .lineTo(545, doc.y)
            .stroke();

        doc.moveDown();

        doc
            .fontSize(18)
            .font("Helvetica-Bold")
            .text("Emergency Incident Report", {
                align: "center"
            });

        doc.moveDown();

        doc.font("Helvetica");

        doc.text(
            `Generated: ${new Date().toLocaleString()}`
        );

        doc.moveDown();

// -------------------------
// SUMMARY
// -------------------------

        doc
            .font("Helvetica-Bold")
            .fontSize(14)
            .text("Report Summary");

        doc.moveDown(.5);

        doc.font("Helvetica");

        doc.text(`Total Reports : ${stats.totalReports}`);
        doc.text(`Pending      : ${stats.pending}`);
        doc.text(`Dispatched   : ${stats.dispatched}`);
        doc.text(`In Progress  : ${stats.inProgress}`);
        doc.text(`Resolved     : ${stats.resolved}`);
        doc.text(`Cancelled    : ${stats.cancelled}`);

        doc.moveDown(2);

// -------------------------
// TABLE HEADER
// -------------------------

        const startY = doc.y;

        doc
            .font("Helvetica-Bold")
            .fontSize(10);

        doc.text("Reference", 50, startY);
        doc.text("Emergency", 150, startY);
        doc.text("Reporter", 250, startY);
        doc.text("Status", 390, startY);
        doc.text("Date", 470, startY);

        doc.moveDown();

        doc
            .moveTo(50, doc.y)
            .lineTo(545, doc.y)
            .stroke();

        doc.font("Helvetica");

// -------------------------
// REPORT LIST
// -------------------------

        reports.forEach(report => {
            if (doc.y > 720) {
                this.addFooter(doc);
                doc.addPage();
            }

            doc.text(
                report.report_reference,
                50,
                doc.y + 5,
                { width: 90 }
            );

            doc.text(
                report.emergency_type,
                150,
                doc.y - 12,
                { width: 90 }
            );

            doc.text(
                report.reporter,
                250,
                doc.y - 12,
                { width: 120 }
            );

            doc.text(
                report.status,
                390,
                doc.y - 12,
                { width: 70 }
            );

            doc.text(
                new Date(report.created_at).toLocaleDateString(),
                470,
                doc.y - 12,
                { width: 70 }
            );

            doc.moveDown();

            doc
                .strokeColor("#dddddd")
                .moveTo(50, doc.y)
                .lineTo(545, doc.y)
                .stroke();
        });

// -------------------------
// FOOTER
// -------------------------

        this.addFooter(doc);
        doc.end();
    }

    static addFooter(doc) {
        doc.fontSize(8);
        doc.text(
            "Generated by SafeConnect",
            50,
            770
        );

        doc.text(
            "Barangay Santa Fe, Dasmarinas, Cavite",
            {
                align: "center"
            }
        );

        doc.text(
            "This document was generated electronically.",
            {
                align: "right"
            }
        );
    }
}

module.exports = PDFService;