// Look of every generated report (Generate Report -> PDF / Excel).
//
// This is the one place to restyle the files: change a color, a line of
// header text or a logo here and every report type picks it up. Colors are
// hex codes ("#RRGGBB"). Logos must be PNG or JPEG files in backend/assets/
// (the backend can't read the frontend's public/ folder once deployed, and
// PDFs can't embed SVG). safeconnect-logo.png is a 600px render of
// public/images/safeconnect-logo.svg -- re-render it if the logo changes.
const path = require("path");

const asset = (file) => path.join(__dirname, "..", "assets", file);

module.exports = {
    // Header block at the top of the first page.
    header: {
        title: "SAFECONNECT",
        lines: [
            "Community Disaster and Emergency Response System",
            "Barangay Santa Fe, Dasmariñas, Cavite"
        ]
    },

    // Left and right logos in the header. If a file is missing, the PDF
    // shows a dashed placeholder circle with `placeholder` written in it.
    logos: {
        left: { file: asset("safeconnect-logo.png"), placeholder: "SafeConnect" },
        right: { file: asset("barangay-logo.png"), placeholder: "Barangay Logo" },
        size: 58 // points (72 points = 1 inch)
    },

    colors: {
        brand: "#780F0F",        // SafeConnect maroon: title, rules, table header
        tableHeaderText: "#FFFFFF",
        text: "#1F2937",
        mutedText: "#6B7280",
        rowStripe: "#F9F4F4",    // every other table row
        gridLine: "#E5E7EB"
    },

    // Built-in PDF fonts: Helvetica, Times-Roman, Courier (+ "-Bold").
    fonts: {
        regular: "Helvetica",
        bold: "Helvetica-Bold",
        size: {
            title: 20,
            subtitle: 10,
            reportTitle: 15,
            body: 10,
            table: 8.5,
            footer: 8
        }
    },

    footer: {
        left: "Generated by SafeConnect",
        right: "This document was generated electronically."
    }
};
